# @package _global_
defaults:
  - override /hydra/launcher: patched_submitit_slurm

# SLURM cluster configuration for Mila
# Remember to also use the resources group to select the resources allocated to the job!
hydra:
  mode: MULTIRUN
  run:
    # output directory, generated dynamically on each run
    dir: ${get_constant:SCRATCH}/ood_slam/logs/${name}/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${get_constant:SCRATCH}/ood_slam/logs/${name}/multiruns
    subdir: ${hydra.job.id}

  launcher:
    timeout_min: 120
    stderr_to_stdout: true
    # Additional SLURM parameters specific to Mila cluster
    additional_parameters:
      account: rrg-lpaull  # Update with your account
