defaults:
  - _self_
  - resources: cpu
  - cluster: null
  - experiment: null

experiment_name: "preprocess_kitti"
name: "${experiment_name}"

data:
  raw_data_dir: "${get_constant:DATA_DIR}/KITTI_raw"
  processed_data_dir: "${get_constant:DATA_DIR}/KITTI"

preprocessing:
  clean_images: true
  create_poses: true
  calculate_stats: true
  train_sequences: ['00', '01', '02', '05', '08', '09']
