_target_: ood_slam.models.DeepVO.DeepVO
img_h: 184  # Image height
img_w: 608  # Image width  
clip: 5.0  # Gradient clipping norm
rnn_hidden_size: 1000
conv_dropout: [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.5]
# conv_dropout: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
rnn_dropout_out: 0.5
# rnn_dropout_out: 0.0
rnn_dropout_between: 0.0
#batch_norm: true
batch_norm: true
# Set this to a path to use pretrained FlowNet weights
# Example: pretrained_flownet: "${get_constant:DATA_DIR}/pretrained/flownets_EPE1.951.pth.tar"
pretrained_flownet: "${get_constant:SLURM_TMPDIR,${get_constant:DATA_DIR}}/KITTI/flownets_EPE1.951.pth"
pretrained_deepvo: "${get_constant:SLURM_TMPDIR,${get_constant:DATA_DIR}}/KITTI/t000102050809_v04060710_im184x608_s5x7_b8_rnn1000_optAdagrad_lr0.0005.model.train"