_target_: ood_slam.models.DeepVO.DeepVO
img_h: 184  # Image height
img_w: 608  # Image width  
clip: 5.0  # Gradient clipping norm
rnn_hidden_size: 1000
conv_dropout: [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.5]
rnn_dropout_out: 0.5
rnn_dropout_between: 0
batch_norm: true
# Set this to a path to use pretrained FlowNet weights
# Example: pretrained_flownet: "${get_constant:DATA_DIR}/pretrained/flownets_EPE1.951.pth.tar"
pretrained_flownet: "${get_constant:SLURM_TMPDIR,${get_constant:DATA_DIR}}/KITTI/flownets_EPE1.951.pth"
